package com.airquality;

import java.io.FileWriter;
import java.io.IOException;

public class ReportGenerator {

    public static void generateReport(AirQualityData data, int aqi, String status) {

        try {
            FileWriter writer = new FileWriter("air_quality_report.txt");

            writer.write("========================================\n");
            writer.write("       AIR QUALITY MONITORING REPORT\n");
            writer.write("========================================\n\n");

            writer.write("Location : " + data.getLocation() + "\n");
            writer.write("PM2.5    : " + data.getPm25() + "\n");
            writer.write("PM10     : " + data.getPm10() + "\n");
            writer.write("CO       : " + data.getCo() + "\n");
            writer.write("NO2      : " + data.getNo2() + "\n\n");

            writer.write("----------------------------------------\n");
            writer.write("AQI      : " + aqi + "\n");
            writer.write("Status   : " + status + "\n");
            writer.write("----------------------------------------\n\n");

            writer.write("Environmental Recommendation:\n");

            if (aqi <= 100) {
                writer.write("Air quality is generally acceptable.\n");
            } else {
                writer.write("Pollution control measures are recommended.\n");
            }

            writer.write("\n========================================\n");
            writer.write("Generated by Air Quality Monitoring System\n");
            writer.write("========================================\n");

            writer.close();

            System.out.println("\nReport generated successfully!");
            System.out.println("File: air_quality_report.txt");

        } catch (IOException e) {
            System.out.println("Error generating report.");
        }
    }
}